version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "35432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
volumes:
  postgres:
